---

- hosts: all 
  become: true
  tasks:
  

  - name: install apache and php packeges and update repo index 
    package: 
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes 

  

      

