---

- hosts: all 
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 packege
    apt: 
      name: apache2  
    when: ansible_distribution == "Ubuntu"

  - name: add php support  apache2 packege
    apt:
      name: libapache2-mod-php
    when: ansible_distribution == "Ubuntu"


  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install httpd packege
    dnf:
      name: httpd
    when: ansible_distribution == "CentOS"

  - name: add php support httpd packege
    dnf:
      name: php
    when: ansible_distribution == "CentOS"

      

